name: online_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  injectable:
  json_annotation:
  shared_preferences:
  ntp:
  dartz:
  package_info:
  google_fonts:
  freezed_annotation:
  dio:
  route_observer_mixin:
  intl:
  expandable:
  html:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  bloc_test:
  freezed:
  injectable_generator:
  json_serializable:
 
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/graphics/
  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Black.otf
      weight: 400
    - asset: assets/fonts/Montserrat-LightItalic.otf
      style: italic
      weight: 400
    - asset: assets/fonts/Montserrat-Bold.otf
      weight: 800
